export interface Customer{
    IdCliente: number;
    Nombre: string;
    NombreComercial: string;
    FechaAlta: Date;
    DNINIF: string;
    Telefono1: string;
    Email1: string;
    Email2: string;
    Email3: string;
    Fax1: string;
    Movil1: string;
    CodFormaPago: number;
    RE: number;
    DtoPP: number;
    DtoComercial: number;
    CodPostal: string;
    Localidad: string;
    Provincia: string;
    Direccion: string;
    Entidad: string;
    Oficina: string;
    DC: string;
    Cuenta: string;
    IBAN: string;
    Observaciones: string;
    CodComercial: number;
    EstadoCliente: number;
}
