"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_1 = require("./auth");
var user_1 = require("./user");
var prod_1 = require("./prod");
var cust_1 = require("./cust");
var paym_1 = require("./paym");
var supp_1 = require("./supp");
var categ_1 = require("./categ");
var subcat_1 = require("./subcat");
var routes = express_1.Router();
routes.use('/auth', auth_1.default);
routes.use('/users', user_1.default);
routes.use('/prod', prod_1.default);
routes.use('/cust', cust_1.default);
routes.use('/paym', paym_1.default);
routes.use('/supp', supp_1.default);
routes.use('/categ', categ_1.default);
routes.use('/subcat', subcat_1.default);
exports.default = routes;
//# sourceMappingURL=index.js.map